syntax = "proto3";

package pb;

option go_package = "github.com/kayden-vs/zaraba/pb";

service Exchange {
    rpc PlaceMarketOrder(Order) returns (Match);
    rpc PlaceLimitOrder(PlaceLimitOrderRequest) returns (Match);
    rpc StreamOrderBook(OrderBookRequest) returns (OrderbookSnapshot);
}

message Order {
    int64 id = 1;
    int64 price = 2; 
    int64 size = 3; // Base asset quantity in integer units
    bool bid = 4;
    Limit limit = 5;
    int64 timestamp = 6;
}

message Limit {
    int64 price = 1; 
    repeated Order orders = 2;
    int64 total_volume = 3; 
}

message PlaceLimitOrderRequest {
    int64 price = 1; 
    Order order = 2;
}

message Match {
    Order ask = 1;
    Order bid = 2;
    int64 sizeFilled = 3; 
    int64 price = 4; 
}

message OrderBookRequest {
    string market = 1;
}

message OrderbookSnapshot {
    repeated Limit asks = 1; 
    repeated Limit bids = 2;
    int64 timestamp = 3;
}