// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: exchange.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// int64 id = 1;
	// int64 price = 2;
	Size          float64 `protobuf:"fixed64,3,opt,name=size,proto3" json:"size,omitempty"`
	Bid           bool    `protobuf:"varint,4,opt,name=bid,proto3" json:"bid,omitempty"`
	Limit         *Limit  `protobuf:"bytes,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Timestamp     int64   `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Order) GetBid() bool {
	if x != nil {
		return x.Bid
	}
	return false
}

func (x *Order) GetLimit() *Limit {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *Order) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Limit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         int64                  `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Orders        []*Order               `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	TotalVolume   float64                `protobuf:"fixed64,3,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limit) Reset() {
	*x = Limit{}
	mi := &file_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limit) ProtoMessage() {}

func (x *Limit) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limit.ProtoReflect.Descriptor instead.
func (*Limit) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *Limit) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Limit) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *Limit) GetTotalVolume() float64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

type PlaceLimitOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         int64                  `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceLimitOrderRequest) Reset() {
	*x = PlaceLimitOrderRequest{}
	mi := &file_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceLimitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceLimitOrderRequest) ProtoMessage() {}

func (x *PlaceLimitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceLimitOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceLimitOrderRequest) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceLimitOrderRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PlaceLimitOrderRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ask           *Order                 `protobuf:"bytes,1,opt,name=ask,proto3" json:"ask,omitempty"`
	Bid           *Order                 `protobuf:"bytes,2,opt,name=bid,proto3" json:"bid,omitempty"`
	SizeFilled    float64                `protobuf:"fixed64,3,opt,name=sizeFilled,proto3" json:"sizeFilled,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *Match) GetAsk() *Order {
	if x != nil {
		return x.Ask
	}
	return nil
}

func (x *Match) GetBid() *Order {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *Match) GetSizeFilled() float64 {
	if x != nil {
		return x.SizeFilled
	}
	return 0
}

func (x *Match) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_exchange_proto protoreflect.FileDescriptor

const file_exchange_proto_rawDesc = "" +
	"\n" +
	"\x0eexchange.proto\x12\bexchange\"r\n" +
	"\x05Order\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x01R\x04size\x12\x10\n" +
	"\x03bid\x18\x04 \x01(\bR\x03bid\x12%\n" +
	"\x05limit\x18\x05 \x01(\v2\x0f.exchange.LimitR\x05limit\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"i\n" +
	"\x05Limit\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x03R\x05price\x12'\n" +
	"\x06orders\x18\x02 \x03(\v2\x0f.exchange.OrderR\x06orders\x12!\n" +
	"\ftotal_volume\x18\x03 \x01(\x01R\vtotalVolume\"U\n" +
	"\x16PlaceLimitOrderRequest\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x03R\x05price\x12%\n" +
	"\x05order\x18\x02 \x01(\v2\x0f.exchange.OrderR\x05order\"\x83\x01\n" +
	"\x05Match\x12!\n" +
	"\x03ask\x18\x01 \x01(\v2\x0f.exchange.OrderR\x03ask\x12!\n" +
	"\x03bid\x18\x02 \x01(\v2\x0f.exchange.OrderR\x03bid\x12\x1e\n" +
	"\n" +
	"sizeFilled\x18\x03 \x01(\x01R\n" +
	"sizeFilled\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price2\x86\x01\n" +
	"\bExchange\x124\n" +
	"\x10PlaceMarketOrder\x12\x0f.exchange.Order\x1a\x0f.exchange.Match\x12D\n" +
	"\x0fPlaceLimitOrder\x12 .exchange.PlaceLimitOrderRequest\x1a\x0f.exchange.MatchB Z\x1egithub.com/kayden-vs/zaraba/pbb\x06proto3"

var (
	file_exchange_proto_rawDescOnce sync.Once
	file_exchange_proto_rawDescData []byte
)

func file_exchange_proto_rawDescGZIP() []byte {
	file_exchange_proto_rawDescOnce.Do(func() {
		file_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exchange_proto_rawDesc), len(file_exchange_proto_rawDesc)))
	})
	return file_exchange_proto_rawDescData
}

var file_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_exchange_proto_goTypes = []any{
	(*Order)(nil),                  // 0: exchange.Order
	(*Limit)(nil),                  // 1: exchange.Limit
	(*PlaceLimitOrderRequest)(nil), // 2: exchange.PlaceLimitOrderRequest
	(*Match)(nil),                  // 3: exchange.Match
}
var file_exchange_proto_depIdxs = []int32{
	1, // 0: exchange.Order.limit:type_name -> exchange.Limit
	0, // 1: exchange.Limit.orders:type_name -> exchange.Order
	0, // 2: exchange.PlaceLimitOrderRequest.order:type_name -> exchange.Order
	0, // 3: exchange.Match.ask:type_name -> exchange.Order
	0, // 4: exchange.Match.bid:type_name -> exchange.Order
	0, // 5: exchange.Exchange.PlaceMarketOrder:input_type -> exchange.Order
	2, // 6: exchange.Exchange.PlaceLimitOrder:input_type -> exchange.PlaceLimitOrderRequest
	3, // 7: exchange.Exchange.PlaceMarketOrder:output_type -> exchange.Match
	3, // 8: exchange.Exchange.PlaceLimitOrder:output_type -> exchange.Match
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_exchange_proto_init() }
func file_exchange_proto_init() {
	if File_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exchange_proto_rawDesc), len(file_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exchange_proto_goTypes,
		DependencyIndexes: file_exchange_proto_depIdxs,
		MessageInfos:      file_exchange_proto_msgTypes,
	}.Build()
	File_exchange_proto = out.File
	file_exchange_proto_goTypes = nil
	file_exchange_proto_depIdxs = nil
}
